void init(void);
int putc(int c);
int getc(void);
int puts(const char *str);
int gets(char *buf);
int strcmp(const char *s1, const char *s2);
int strncmp(const char *s1, const char *s2, int len);
void rand_init(void);
unsigned int rand(unsigned int min, unsigned int max);
void on(int n);
void off(int n);
void start(void);
void help(void);
