void init(void);
int putc(unsigned char c);
unsigned char getc(void);
int puts(unsigned char *str);
int gets(unsigned char *buf);
int strcmp(const char *s1, const char *s2);
int strncmp(const char *s1, const char *s2, int len);
void rand_init(void);
unsigned int rand(unsigned int min, unsigned int max);
void on(unsigned int n);
void off(unsigned int n);
void in(void);
void start(void);
void help(void);
